/*
   **********************************************
   SQLs de Análise Geral das Leituras de Guias
   **********************************************
*/


--fdqCadastro

SELECT
  GUIA.*,
  CABEC.SEQUENCIAL_TRANSACAO,
  TP.DESCRICAO AS  "TIPO_SERVICO",
  STATUS.DESCRICAO AS STATUS,
  USUARIO.LOGIN,
  GRUPO.DT_IMPORTACAO,
  GRUPO.HR_IMPORTACAO
FROM GUIAS_DETALHE GUIA
INNER JOIN GUIAS_CABECALHO CABEC ON (CABEC.ID_GUIAS_CABECALHO = GUIA.ID_GUIAS_CABECALHO)
INNER JOIN GUIAS_GRUPO_LOTE GRUPO ON (GRUPO.ID_GUIAS_GRUPO_LOTE = CABEC.ID_GUIAS_GRUPO_LOTE)
INNER JOIN TIPO_SERVICO TP ON (TP.ID_TIPO_SERVICO = GRUPO.ID_TIPO_SERVICO)
LEFT OUTER JOIN LEITURA_STATUS STATUS ON (STATUS.ID_LEITURA_STATUS = GUIA.ID_LEITURA_STATUS)
LEFT OUTER JOIN USUARIO ON (USUARIO.ID_USUARIO = GRUPO.ID_USUARIO)
WHERE GUIA.ID_GUIAS_DETALHE =:ID_GUIAS_DETALHE


--query da tela
SELECT
  GUIA.*,
  CABEC.SEQUENCIAL_TRANSACAO,
  TP.DESCRICAO AS  "TIPO_SERVICO",
  STATUS.DESCRICAO AS STATUS
FROM GUIAS_DETALHE GUIA
INNER JOIN GUIAS_CABECALHO CABEC ON (CABEC.ID_GUIAS_CABECALHO = GUIA.ID_GUIAS_CABECALHO)
INNER JOIN GUIAS_GRUPO_LOTE GRUPO ON (GRUPO.ID_GUIAS_GRUPO_LOTE = CABEC.ID_GUIAS_GRUPO_LOTE)
INNER JOIN TIPO_SERVICO TP ON (TP.ID_TIPO_SERVICO = GRUPO.ID_TIPO_SERVICO)
LEFT OUTER JOIN LEITURA_STATUS STATUS ON (STATUS.ID_LEITURA_STATUS = GUIA.ID_LEITURA_STATUS)
LEFT OUTER JOIN USUARIO ON (USUARIO.id_usuario = GRUPO.id_usuario)
WHERE 1=1
AND CABEC.SEQUENCIAL_TRANSACAO = :SEQUENCIAL_TRANSACAO
AND GUIA.DATA = :DATA
AND GRUPO.ID_TIPO_SERVICO = :ID_TIPO_SERVICO
AND GUIA.ID_LEITURA_STATUS = :ID_LEITURA_STATUS
AND GUIA.NUMERO_CARTEIRA = :NUMERO_CARTEIRA
AND GUIA.NUMERO_GUIA_PRESTADOR = :NUMERO_GUIA_PRESTADOR


SELECT DISTINCT(CABEC.SEQUENCIAL_TRANSACAO)
FROM GUIAS_CABECALHO CABEC
ORDER BY CABEC.SEQUENCIAL_TRANSACAO






SELECT
  GUIA.*,
  CABEC.SEQUENCIAL_TRANSACAO,
  TP.DESCRICAO AS  "TIPO_SERVICO",
  STATUS.DESCRICAO AS STATUS
FROM GUIAS_DETALHE GUIA
INNER JOIN GUIAS_CABECALHO CABEC ON (CABEC.ID_GUIAS_CABECALHO = GUIA.ID_GUIAS_CABECALHO)
INNER JOIN GUIAS_GRUPO_LOTE GRUPO ON (GRUPO.ID_GUIAS_GRUPO_LOTE = CABEC.ID_GUIAS_GRUPO_LOTE)
INNER JOIN TIPO_SERVICO TP ON (TP.ID_TIPO_SERVICO = GRUPO.ID_TIPO_SERVICO)
LEFT OUTER JOIN LEITURA_STATUS STATUS ON (STATUS.ID_LEITURA_STATUS = GUIA.ID_LEITURA_STATUS)
WHERE GUIA.ID_GUIAS_DETALHE =:ID_GUIAS_DETALHE







--QUERY LEITURA
SELECT
  GUIA.*,
  CABEC.sequencial_transacao,
  TP.descricao as  "Tipo_Servico"
FROM GUIAS_DETALHE GUIA
INNER JOIN GUIAS_CABECALHO CABEC ON (CABEC.ID_GUIAS_CABECALHO = GUIA.ID_GUIAS_CABECALHO)
INNER JOIN guias_grupo_lote GRUPO ON (GRUPO.id_guias_grupo_lote = CABEC.id_guias_grupo_lote)
INNER JOIN TIPO_SERVICO TP ON (TP.id_tipo_servico = GRUPO.id_tipo_servico)
WHERE GUIA.DATA =  :DATA
AND GUIA.NUMERO_CARTEIRA = :NUMERO_CARTEIRA
AND COALESCE(GUIA.LIDA,'FALSE') = 'FALSE'
AND COALESCE(CABEC.FINALIZADO,'FALSE') = 'FALSE'
AND COALESCE(CABEC.CANCELADO,'FALSE') = 'FALSE'

--QUERY DE GUIAS LIDAS
SELECT
  GUIA.*,
  CABEC.SEQUENCIAL_TRANSACAO,
  TP.DESCRICAO AS  "TIPO_SERVICO",
  STATUS.DESCRICAO AS STATUS
FROM GUIAS_DETALHE GUIA
INNER JOIN GUIAS_CABECALHO CABEC ON (CABEC.ID_GUIAS_CABECALHO = GUIA.ID_GUIAS_CABECALHO)
INNER JOIN GUIAS_GRUPO_LOTE GRUPO ON (GRUPO.ID_GUIAS_GRUPO_LOTE = CABEC.ID_GUIAS_GRUPO_LOTE)
INNER JOIN TIPO_SERVICO TP ON (TP.ID_TIPO_SERVICO = GRUPO.ID_TIPO_SERVICO)
LEFT OUTER JOIN LEITURA_STATUS STATUS ON (STATUS.ID_LEITURA_STATUS = GUIA.ID_LEITURA_STATUS)
WHERE GUIA.DATA =  :DATA
AND COALESCE(GUIA.LIDA,'FALSE') = 'TRUE'
AND COALESCE(CABEC.FINALIZADO,'FALSE') = 'FALSE'
AND COALESCE(CABEC.CANCELADO,'FALSE') = 'FALSE'
ORDER BY GUIA.HORA_LEITURA DESC




--cabecalho
select * from guias_cabecalho cabec
where cabec.sequencial_transacao = 21388 ;

--guias disponiveis 01/10
select DET.numero_carteira from guias_detalhe det
where det.id_guias_cabecalho = 295
and COALESCE(det.lida,'FALSE') = 'FALSE';


select * from guias_detalhe det
where det.id_guias_cabecalho = 295
and COALESCE(det.lida,'FALSE') = 'FALSE';



--guias lidas 01/10
select * from guias_detalhe det
where det.id_guias_cabecalho = 295
and det.lida = 'TRUE';



select * from guias_detalhe det
where det.valor <> det.valortotal_2
and det.id_guias_cabecalho = 295;




UPDATE guias_detalhe det
SET DET.id_leitura_status = NULL;


select * from leitura_status status
order by status.id_leitura_status


select * from leitura_status status
order by status.id_leitura_status
status.descricao

