/******************************************************************************/
/***               Generated by IBExpert 29/10/2014 10:21:49                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE USUARIO (
    ID_USUARIO  INTEGER NOT NULL,
    LOGIN       DO_VARCHAR_20 NOT NULL /* DO_VARCHAR_20 = VARCHAR(20) */,
    NOME        DO_VARCHAR_50 /* DO_VARCHAR_50 = VARCHAR(50) */,
    SENHA       DO_VARCHAR_20 /* DO_VARCHAR_20 = VARCHAR(20) */,
    "ADMIN"     DO_BOOLEAN DEFAULT 'N' /* DO_BOOLEAN = VARCHAR(5) DEFAULT 'FALSE' */,
    ATIVO       DO_BOOLEAN DEFAULT 'S' NOT NULL /* DO_BOOLEAN = VARCHAR(5) DEFAULT 'FALSE' */
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
